on:
  push:
    tags:
      - '*'

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.18.0"
      - name: build
        run: |
          make build
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: output/*